### PR TITLE
Use Mini-asset

### PR DESCRIPTION
**Pull request by markstory**
I've split out the core functionality of this plugin into a standalone library - [mini asset](https://github.com/markstory/mini-asset). My goal in doing this is two fold:

* Insulate asset compress from changes in CakePHP.
* Make asset compress like features available to non-CakePHP applications. I currently use a fork of AssetCompress at work, and I selfishly want to maintain less code.

### TODO

* [x] Fix path resolution for Sprockets filter by using the cake friendly scanner.
* [x] Fix path resolution for ImportInline filter
* [x] Restore tests for AssetScanner and theme/plugin path resolution.

### CODE REVIEW

**Comment by Graziel** [comment]
merge broke my previously working local dev on windows now i get requests like this with errors:
```
http://localhost:81/css/G%3A/resources/pages/project%20cake3/webroot/cache_css/not_logged_in.css?theme=ThemeDefault
Error: CssController could not be found. 
```
while i see the ToDo's list and css is in theme the js is not:

```
http://localhost:81/js/G%3A/resources/pages/project%20cake3/webroot/cache_js/base.js
Error: JsController could not be found. 
```

**Comment by markstory** [comment]
Looks like the full path is being included on windows.

**Comment by Graziel** [comment]
i got to point where paths are ok but now even with debug = true its still trying to compress the file instead of normal appending files and outputing them (like it worked before merge) - the fix ive found is delete the filters[] in .ini

to fix routes change $path = str_replace(WWW_ROOT, '', $path) to:
```
$root = str_replace('\\', '/', WWW_ROOT);
        $path = str_replace('\\', '/', $path);
        $path = str_replace($root, '', $path);
```
in AssetCompressorFilter.php getName and in AssetCompressHelper.php url

**Comment by markstory** [comment]
Ok. Thanks for the help on the windows issue. I will look into the missing debug toggle too.

**Comment by markstory** [comment]
@Graziel Both those issues should be fixed now. If you could open new issues for any other problems you have it would be appreciated :smile:

**Pull request merged**
