### PR TITLE
Fix auto include functionality

### PR DESCRIPTION
**Pull request by deizel**
Never tried [this functionality][1] before, but it required a few changes to get it working on the 3.0 branch.

[1]: https://github.com/markstory/asset_compress/wiki/Asset-Compress-Helper#auto-include-view-and-controller-javascript-files

### CODE REVIEW

**Comment by markstory** [comment]
I was thinking of just delete this code, its a pretty janky feature.

**Comment by deizel** [comment]
Makes sense, this feature doesn't currently filter assets anyway, which is the primary aim of this plugin.

So without any plans to improve it, might be best to drop the functionality and deprecate it in the wiki?

**Comment by markstory** [comment]
Killing this feature in #257

**Comment by deizel** [comment]
:+1:

**Pull request closed without merging**
