### PR TITLE
Cache config documentation

### PR DESCRIPTION
**Pull request by AltamashShaikh**
Have added documentation to specify cacheconfig like Redis,Memcache etc

### CODE REVIEW

**Comment by markstory** [comment]
This includes the change I proposed in #308. Did you intend to include it here?

**Comment by AltamashShaikh** [comment]
Yes,since it all started with this thread ao thought of taking chexkout of
this branch, if you want will create a new pull request and checkout a
branch from master.

What do you suggest?

**Comment by markstory** [comment]
It is ok, everything is merged in now and released as 0.23.

**Comment by AltamashShaikh** [comment]
Oh nice!

Thanks alot :)

**Pull request merged**
