### PR TITLE
Modified stdin from - to --

### PR DESCRIPTION
**Pull request by Jeraimee**
This allows AssetCompress to work with the newer UglifyJS2.

### CODE REVIEW

**Comment by markstory** [comment]
Looks like a lot more changes than what you originally intended. Any way to clean that up?

**Comment by Jeraimee** [comment]
That's quite strange. I didn't even check the branch out. I made the edit in the single Lib/Filter/Uglifyjs.php file in the Github editor (since I was just adding a "-"). Not sure why stickler thinks I made all those changes (and I certainly wouldn't use tabs! ;) )

**Comment by markstory** [comment]
@Jeraimee Are you looking to update the cakephp 2.x compatible version of asset compress?

**Comment by Jeraimee** [comment]
Yes, I was in the 2.x branch.

**Comment by markstory** [comment]
Thanks @Jeraimee

**Comment by markstory** [comment]
Closing as #304 was merged.

**Pull request closed without merging**
